Repository SOPT-all/35-APPJAM-iOS-GONGBAEK, pull requests merged in 2025-01, with the labels that each got.

#2 [Setting] #1 - 에셋 세팅
  Gongbaek_iOS/Gongbaek-iOS-Info.plist
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Font+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Text+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_01.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_02.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_03.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_04.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_05.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_06.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_07.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_08.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_09.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_10.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_black.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Grayscale/gray_white.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Primary/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Primary/main_orange.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Secondary/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Secondary/sub_blue.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Secondary/sub_green.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Secondary/sub_orange.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/Secondary/sub_yellow.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/System/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Color/System/error_red.colorset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Fonts/FontFamily.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Fonts/Pretendard-Bold.otf
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Fonts/Pretendard-Medium.otf
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Fonts/Pretendard-Regular.otf
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Fonts/Pretendard-SemiBold.otf
Labels: 🤯 희은, ⚙️ Setting

#10 [Setting] #9 - caption2 폰트 추가
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Fonts/FontFamily.swift
Labels: 🤯 희은, 🏠 Chore

#7 [Feat] #5 - Button 컴포넌트 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Application/Gongbaek_iOSApp.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/BottomSheet/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/AddMeetingButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CategoryButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CategoryImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CounterButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CoverImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CycleButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/SmallButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/ToggleButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Modal/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_plus_24.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_plus_24.imageset/ic_plus_orange_24.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_plus_24.imageset/ic_plus_orange_24@2x.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_plus_24.imageset/ic_plus_orange_24@3x.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/sample.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/sample.imageset/_ (19) 1.jpeg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/sample.imageset/_ (19) 2.jpeg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/sample.imageset/_ (19).jpeg
Labels: 🧤 민서, 🧩 Feat

#8 [Setting] #6 - 프로젝트 초기 세팅 및 폴더링 세분화
  .gitignore
  Gongbaek_iOS/Gongbaek-iOS-Info.plist
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Network/Base/BaseResponse.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Base/BaseTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Base/NetworkProvider.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/APIConstants.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/Config.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/EmptyResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/MoyaLoggingPlugin.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Filling/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Home/GetUpcomingMeetingResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/Providers.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/HomeTargetType.swift
Labels: 🎐 나연, ⚙️ Setting

#16 [Feat] #13 - 내 몫의 Chip component 생성하기 !
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/MajorChip.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/OwnerChip.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/ProfileDetailChip.swift
Labels: 🤯 희은, 🧩 Feat

#22 [Fix/#21] error fixxxx
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/ProfileDetailChip.swift
Labels: 🤯 희은, 🛠️ Fix

#20 [Feat] #19 - 댓글 Cell Component 작성..
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentCell.swift
Labels: 🤯 희은, 🧩 Feat

#30 [Feat] #23 신청하기 Bar 생성
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/ApplyBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/MajorChip.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentCell.swift
Labels: 🤯 희은, 🧩 Feat

#31 [Feat] #27 - CustomTextEditor 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextEditor.swift
Labels: 🧤 민서, 🧩 Feat

#38 Feat/#37 기본 베이직 버튼 생성
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/BasicButton.swift
Labels: 🤯 희은, 🧩 Feat

#33 [Feat] #24 - segment control component
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/CustomSegmentControlBar.swift
Labels: 🤯 희은, 🧩 Feat

#34 [Feat] #26 - 프로필 박스들 컴포넌트 제작 완료
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/MemberProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/OwnerProfileBox.swift
Labels: 🤯 희은, 🧩 Feat

#35 [Feat] #32 - Alert 창 component화 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Alert/CustomAlert.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Modal/.gitkeep
Labels: 🤯 희은, 🧩 Feat

#41 [Feat] #39 - BasicButton 활용 Bar 생성 완료.
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/ApplyBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/OnboardingConfirmBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/BasicButton.swift
Labels: 🤯 희은, 🧩 Feat

#36 [Feat] #28 - 커스텀 캘린더 컴포넌트 UI 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/CustomCalendar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
Labels: 🧤 민서, 🧩 Feat

#43 [Feat] #29 - List 컴포넌트 UI 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/LocationBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/PersonBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/TimeBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/MyFillCellButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MeetingInfoState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/WeekFullDay.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
Labels: 🧤 민서, 🧩 Feat

#55 [Fix] #54 - Extension 오류 해결
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
Labels: 🧤 민서, 🛠️ Fix

#45 [Feat] #44 - SearchTextField 컴포넌트 UI 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/SearchTextField.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/SearchTextFieldState.swift
Labels: 🧤 민서, 🧩 Feat

#48 [Feat] #46 - CustomTextField 컴포넌트 UI 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextField.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TextFieldState.swift
Labels: 🧤 민서, 🧩 Feat

#56 [Feat] #12 - 온보딩/모임 모집하기 시간표 UI, 기능 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/AddMeetingTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/Model/TimeTableCellId.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/Model/TimeTableModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/OnboardingTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/OnboardingTimeTableExample.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/ViewModeTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TimeTableEnums.swift
Labels: 🎐 나연, 🧩 Feat

#67 [Fix/#66] TitleTextBox에 subtitle 없는 경우 추가
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/TitleTextBox.swift
Labels: 🤯 희은, 🛠️ Fix

#64 [Feat] #49 - 채우기 UI 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/CategoryBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/WeekFilterBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CategoryImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/ToggleButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/MeetingChip.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/CategoryState.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/Model/FillingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingList.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/ViewModel/FillingViewModel.swift
Labels: 🧤 민서, 🧩 Feat

#68 [Feat] #63 - 내비게이션바 UI 구현 및 내비게이션 스택 관리 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomNavigationBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomTabBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/TabBar/TabBarView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/View+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/TabBarView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic__x_48.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_arrow_left_48.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Presentation/ContentView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/HomeView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ProfileSelectionView.swift
Labels: 🎐 나연, 🧩 Feat

#58 [Feat] #53 - YearSelectButton 컴포넌트 UI 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/YearSelectButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
Labels: 🧤 민서, 🧩 Feat

#69 [Feat] #59 - Meeting Detail View UI 생성
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/ApplyBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/CustomSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/MeetingDetailSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/MyFillSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/MemberProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/OwnerProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/Model/CommentModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/Model/MeetingDetailModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/Model/OwnerInfoModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/CommentView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingInfoView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
Labels: 🤯 희은, 🧩 Feat

#72 [Feat] #65 - 모임 모집하기 UI 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Application/Gongbaek_iOSApp.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/PersonCountBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/SelectedTimeBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CategoryImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/CustomCalendar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/AddMeetingTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/Model/TimeTableModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextEditor.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/CategoryState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/CycleState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TimeTableEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/WeekFullDay.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Double+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/TabBarView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Image.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_dining.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_dining.imageset/Property 1=2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_exercise.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_exercise.imageset/Property 1=3.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_networking.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_networking.imageset/Property 1=4.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_others.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_others.imageset/Property 1=6.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_play.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_play.imageset/Property 1=5.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_study.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_category_study.imageset/Property 1=1.svg
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/Model/AddMeetingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CalendarSelectView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CategorySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CheckInputInfo.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CoverImageSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/IntroduceInput.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/LocationInput.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/TimeSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/WeekDaySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/ViewModel/AddMeetingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/Model/FillingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingView.swift
Labels: 🧤 민서, 🧩 Feat

#74 [Feat] #60 - 회원가입 로직 UI 구현 ...
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/OnboardingConfirmBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/ProgressBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/BasicButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CoverImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/MajorDirectRegistrationButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/SmallButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/YearSelectButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/SearchListCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/OnboardingTimeTableExample.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextEditor.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/SearchTextField.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/SearchViewState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/SignupEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_0.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_0.imageset/profile_image_0.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_1.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_1.imageset/profile_image_1.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_2.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_2.imageset/profile_image_2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_3.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_3.imageset/profile_image_3.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_4.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_4.imageset/profile_image_4.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_5.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/profile_image_5.imageset/profile_image_5.svg
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/Model/MajorNameListModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/Model/SchoolNameListModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ClassTimeTableInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/FreeTimeTableConversionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/GradeAdmissionYearInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/MbtiSelectionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/NicknameInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ProfileSelectionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorSearchView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SelfIntroductionWritingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SexSelectionView.swift
Labels: 🎐 나연, 🧩 Feat

#84 [Chore] #77 - 변경된 icon image 수정
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MeetingChipState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_fire_18.imageset/ic_fire_18.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_fire_18.imageset/ic_fire_18@2x.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_fire_18.imageset/ic_fire_18@3x.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_lock_18.imageset/ic_lock_18.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_lock_18.imageset/ic_lock_18@2x.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_lock_18.imageset/ic_lock_18@3x.png
Labels: 🤯 희은, 🏠 Chore

#78 [Refactor] #76 - 회원가입 뷰 하나로 리팩토링 및 회원가입 뷰모델 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomNavigationBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/MemberProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/MeetingChip.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/SearchTextField.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/SignupEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/View+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/SignupNavigationView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CalendarSelectView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CategorySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CheckInputInfo.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CoverImageSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/IntroduceInput.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/LocationInput.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/TimeSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/WeekDaySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/Model/SchoolNameListModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ClassTimeTableInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/FreeTimeTableConversionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/GradeAdmissionYearInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/MbtiSelectionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/NicknameInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ProfileSelectionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorSearchView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SelfIntroductionWritingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SexSelectionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupCompletionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/ViewModel/SignupViewModel.swift
Labels: 🎐 나연, 🧩 Feat, 🌱 Refactor

#83 [Feat] #61 - 나의 채움 UI 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/MyFillSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_fire_18.imageset/ic_fire_18.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_fire_18.imageset/ic_fire_18@2x.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_fire_18.imageset/ic_fire_18@3x.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_lock_18.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_lock_18.imageset/ic_lock_18@3x 1.png
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Empty/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Empty/img_myFill_empty_active.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Empty/img_myFill_empty_active.imageset/img_my_fill_empty_action.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Empty/img_myFill_empty_end.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Empty/img_myFill_empty_end.imageset/img_my_fill_empty_end.svg
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/Model/FillingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingList.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/MyFillingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/View/MyFillingEmptyCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/View/MyFillingHeader.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/View/MyFillingList.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/View/MyFillingView.swift
Labels: 🧤 민서, 🧩 Feat

#85 [Feat] #75 - 온보딩 UI 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_onboarding_1.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_onboarding_1.imageset/img_onboard_illustration1.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_onboarding_2.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_onboarding_2.imageset/img_onboard_illustration2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_onboarding_3.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_onboarding_3.imageset/img_onboard_illustration3.svg
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingIndicator.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingNavigation.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingPageView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingView.swift
Labels: 🧤 민서, 🧩 Feat

#81 [Feat] #79 - 홈화면 UI 및 뷰모델 상태값 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/TitleTextBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/HomeMatchMemberListCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/HomeMeetingCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_home_banner.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_home_banner.imageset/img_home_banner.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_home_main.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/img_home_main.imageset/img_home_main.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Fonts/HighlightTextView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CategorySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/Model/MeetingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/Model/PerfectMatchMemberModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/HomeView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/ViewModel/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: 🎐 나연, 🧩 Feat

#88 Feat/#82 Button 5분할 logic 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/ApplyBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingInfoView.swift
Labels: 🤯 희은, 🧩 Feat

#92 [Refactor] #90 - 모임방 뷰모델 리팩토링
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/ViewModel/MeetingRoomViewModel.swift
Labels: 🤯 희은, 🌱 Refactor

#89 [Refactor] #86 - navigation 로직! 찍!
  Gongbaek_iOS/Gongbaek_iOS/Application/Gongbaek_iOSApp.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/RootViewSwitcher.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/SignupNavigationView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/TabBarView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
Labels: 🎐 나연, 🧩 Feat, 🌱 Refactor

#101 [Network] #95 - 회원가입 API 연결
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Literal/String.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/APIConstants.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/MoyaLoggingPlugin.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Signup/GetSearchResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Signup/PostSignupRequestDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Signup/PostSignupResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/Providers.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/SignupTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorSearchView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/ViewModel/SignupViewModel.swift
Labels: 🎐 나연, 🌐 Network

#106 [Network] #87 - 모임 모집하기 네트워크 통신
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/AddMeetingTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/Model/TimeTableModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/CategoryState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_lock_18.imageset/ic_lock_18.png
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/APIConstants.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Filling/.gitkeep
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Filling/GetTimeTableResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Filling/PostMeetingRequestDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/Providers.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/FillingTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/Model/AddMeetingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/TimeSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/ViewModel/AddMeetingViewModel.swift
Labels: 🧤 민서, 🌐 Network

#105 [Network] #96 - 나의 채움 네트워크 통신
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/MyFillSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/CategoryState.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Filling/GetMyFillingResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingList.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/MyFillingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/View/MyFillingList.swift
Labels: 🧤 민서, 🌐 Network

#108 [Network] #102 - 홈화면 API 연결
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CoverImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Error/FullErrorView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/HomeMatchMemberListCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/HomeMeetingCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/CategoryState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/GroupState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/ImageMapEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/SignupEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Home/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Home/img_home_banner.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Home/img_home_banner.imageset/img_home_banner.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Home/img_home_main.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Home/img_home_main.imageset/img_home_main.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Onboarding/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Onboarding/img_onboarding_1.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Onboarding/img_onboarding_1.imageset/img_onboard_illustration1.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Onboarding/img_onboarding_2.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Onboarding/img_onboarding_2.imageset/img_onboard_illustration2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Onboarding/img_onboarding_3.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Onboarding/img_onboarding_3.imageset/img_onboard_illustration3.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_0.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_0.imageset/profile_image_0.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_1.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_1.imageset/profile_image_1.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_2.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_2.imageset/profile_image_2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_3.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_3.imageset/profile_image_3.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_4.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_4.imageset/profile_image_4.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_5.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_5.imageset/profile_image_5.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_0.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_0.imageset/img_profile_default_0.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_1.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_1.imageset/img_profile_default_1.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_2.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_2.imageset/img_profile_default_2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_3.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_3.imageset/img_profile_default_3.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_4.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_4.imageset/img_profile_default_4.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_5.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_5.imageset/img_profile_default_5.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Response/img_error.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Response/img_error.imageset/img_error.svg
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Home/GetJoinableMeetingListResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Home/GetUpcomingMeetingResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Home/GetUserProfileResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/HomeTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CheckInputInfo.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/ViewModel/AddMeetingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/HomeView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ProfileSelectionView.swift
Labels: 🎐 나연, 🌐 Network

#115 [Feat] #103 - 탭바 루트뷰 변경 기능 추가, 수업 -> 공강 시간표 변환 함수 추가
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/OwnerProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CoverImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Error/FullErrorView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/HomeMatchMemberListCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/HomeMeetingCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/AddMeetingTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/CategoryState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/GroupState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/ImageMapEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/TabBarView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_0.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_0.imageset/profile_image_0.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_1.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_1.imageset/profile_image_1.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_2.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_2.imageset/profile_image_2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_3.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_3.imageset/profile_image_3.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_4.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_4.imageset/profile_image_4.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_5.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_button_5.imageset/profile_image_5.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_0.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_0.imageset/Property=1.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_1.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_1.imageset/Property=2.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_2.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_2.imageset/Property=3.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_3.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_3.imageset/Property=4.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_4.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_4.imageset/Property=5.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_5.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Profile/img_profile_default_5.imageset/Property=6.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Response/img_error.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Response/img_error.imageset/img_error.svg
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Home/GetJoinableMeetingListResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Home/GetUpcomingMeetingResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Home/GetUserProfileResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Signup/GetSearchResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Signup/PostSignupRequestDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Signup/PostSignupResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/HomeTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/SignupTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CheckInputInfo.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/TimeSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/ViewModel/AddMeetingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/HomeView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ProfileSelectionView.swift
Labels: 🎐 나연, 🧩 Feat, 🛠️ Fix

#116 [Fix] #103 - 회원가입 API 코드 복구
  Gongbaek_iOS/Gongbaek_iOS/Global/Literal/String.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/Model/SchoolNameListModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorSearchView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/ViewModel/SignupViewModel.swift
Labels: 🎐 나연, 🛠️ Fix

#117 [Feat] #111 - 네비게이션 스택 쌓기 ..
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomNavigationBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/MemberProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/OwnerProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/MyFillCellButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/CustomCalendar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/TabBarView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/HomeView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
Labels: 🤯 희은, 🧩 Feat

#118 [Feat] #114 - 에러 대응 뷰 추가
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/MyFillSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/AddMeetingTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Response/img_congratulation.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Response/img_congratulation.imageset/img_congratulation.png
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/ViewModel/FillingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/MyFillingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/View/MyFillingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorSearchView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupCompletionView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/ViewModel/SignupViewModel.swift
Labels: 🧤 민서, 🧩 Feat

#121 [Feat] #103 - 바텀시트 화면 연결 및 데이터 바인딩
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/BottomSheet/YearSelectBottomSheet.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/YearSelectButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/SignupEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/RootViewSwitcher.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/GradeAdmissionYearInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
Labels: 🎐 나연, 🧩 Feat, 🛠️ Fix

#123 [Feat] #119 - 에러 대응 뷰 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentList.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/CommentView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/ViewModel/MeetingRoomViewModel.swift
Labels: 🤯 희은, 🧩 Feat

#125 [Network] #124 - patch/delete apply meeting
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/MeetingDetailTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
Labels: 🤯 희은, 🧩 Feat

#127 [Fix] #120 - CustomNavigationBar 수정
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomNavigationBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/View+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/Model/FillingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/ViewModel/FillingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/ViewModel/MeetingRoomViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/MyFillingViewModel.swift
Labels: 🧤 민서, 🧩 Feat

#126 [Setting] #122 - 테스트플라이트 배포 준비 및 자잘한 바인딩 문제 해결
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/xcshareddata/xcschemes/Gongbaek_iOS.xcscheme
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/OnboardingTimeTable.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Others/TimeTable/OnboardingTimeTableExample.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/logo.png
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/APIConstants.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/ClassTimeTableInputView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/ViewModel/SignupViewModel.swift
Labels: 🎐 나연, 🛠️ Fix, ⚙️ Setting

#133 [Refactor] #130 - QA 수정
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/HomeView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/CommentView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingInfoView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
Labels: 🤯 희은, 🌱 Refactor

#137 [Fix] #135 - refactor button
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentList.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CommentTextField.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/CommentView.swift
Labels: 🤯 희은, 🌱 Refactor

#139 [Hot Fix] #138 - Navigation Fix
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
Labels: 🤯 희은, 🛠️ Fix

#143 [Feat] #142 - 자동로그인 구현 전 회원가입 건너뛰기 투명 비밀 버튼 구현
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingNavigation.swift
Labels: 🎐 나연, 🧩 Feat
